Edited port

diff --git a/pwd.yml b/pwd.yml
--- a/pwd.yml
+++ b/pwd.yml
@@ -78,11 +78,20 @@ services:
         done;
         echo "sites/common_site_config.json found";
         bench new-site --mariadb-user-host-login-scope='%' --admin-password=admin --db-root-username=root --db-root-password=admin --install-app erpnext --set-default frontend;
-        cd /home/frappe/frappe-bench/apps;
-        bench get-app hrms;
-        bench --site frontend list-apps;
-        bench --site frontend install-app hrms;
-        bench migrate --skip-failing;
+        # cd /home/frappe/frappe-bench/apps;
+        # bench get-app hrms;
+        # bench --site frontend list-apps;
+        # bench --site frontend install-app hrms;
+        # bench migrate --skip-failing;
+        #############################################################
+        # if ! bench --site frontend list-apps | grep -q "hrms"; then
+        #   echo "HRMS app not found, installing...";
+        #   cd /home/frappe/frappe-bench/apps;
+        #   bench get-app hrms;
+        #   bench --site frontend list-apps;
+        #   bench --site frontend install-app hrms;
+        #   bench migrate --skip-failing
+        # fi;
   db:
     image: mariadb:10.6
     networks:
@@ -129,7 +138,7 @@ services:
       - sites:/home/frappe/frappe-bench/sites
       - logs:/home/frappe/frappe-bench/logs
     ports:
-      - "8080:8080"
+      - "9090:8080"
 
   queue-long:
     image: frappe/erpnext:v15.63.0
